language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="appstream desktop-file-utils meson libgtk-3-dev libglib2.0-dev libgranite-dev libbamf3-dev libwnck-3-dev libgtop2-dev"

install:
 - docker pull elementary/docker:loki
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja"
 - docker pull elementary/docker:loki-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki-unstable /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && rm -rf build && meson build --prefix=/usr && cd build && ninja"

script:
- echo BUILDS PASSED